### ISSUE TITLE
Too hipster

### ISSUE THREAD

**Issue by jonotrujillo** [cskeppstedt/redux-observables-talk#1]
This talk is too hipster.

k, bye.

**Comment by cskeppstedt** [comment]
It's possible. But, have you seen the app yet? https://cskeppstedt.github.io/redux-observables-talk/

**Comment by jonotrujillo** [comment]
![sunglasses-off-loop](https://user-images.githubusercontent.com/313951/32270246-5e27c634-bef5-11e7-877a-6e9adeea39b2.gif)
